name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  some-ci-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: multiline test script
        run: |
          echo "line 1"
          echo "line 2"
          false
          echo "line 3"
