name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Build local v
        run: make -j4
      - name: multiline test script
        run: |
          echo "line 1"
          echo "line 2"
          false
          echo "line 3"
